version: '2'

services:
  cron-serv:
    image: docker-crontab:python${PYTHON_VER}
    build:
      context: .
      dockerfile: Dockerfile.python${PYTHON_VER}
      args:
        PROJ_CONF_DIR: /etc/circus
        PROJ_SRC_DIR: /cron-server
        PIP_REQUIRE_DIR: ./src
    volumes:
      - ./sample_crontab:/sample_crontab
    environment:
      - TZ=${TZ}
      - crontab_paths=/sample_crontab/test.crontab
      - CIRCUS_LOG_LEVEL=debug
