FROM python3-base
ARG TZ
ENV TZ=${TZ:-Asia/Taipei}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y bash-completion && apt-get clean
RUN pip install --no-cache-dir ipython pudb pydevd
CMD bash