version: '2'

services:
  cron-serv:
    image: cron-serv
    build:
      context: .
      args:
        PROJ_CONF_DIR: /sample_crontab
        PROJ_SRC_DIR: /src
        PIP_REQUIRE_DIR: ./src/
      dockerfile: Dockerfile.dev
    volumes:
      - ./sample_crontab:/sample_crontab
      - ./src:/src
    environment:
      TZ: $TZ
    entrypoint:
