version: '2'

services:
  cron-serv-dev-cli:
    image: cron-serv-dev:python${PYTHON_VER}
    build:
      context: .
      dockerfile: Dockerfile.python${PYTHON_VER}.dev
      args:
        PROJ_CONF_DIR: /sample_crontab
        PROJ_SRC_DIR: /cron-server
        PIP_REQUIRE_DIR: ./src
    volumes:
      - ./sample_crontab:/sample_crontab
      - ./src:/cron-server
    environment:
      TZ: $TZ
      crontab_paths: /sample_crontab
    entrypoint: bash