FROM python2-base
ARG TZ
ENV TZ=${TZ:-Asia/Taipei}
RUN DEBIAN_FRONTEND=noninteractive apt-get update\
 && DEBIAN_FRONTEND=noninteractive apt-get install -y bash-completion git
RUN pip install --no-cache-dir ipython pip-review pudb pydevd ptvsd
CMD bash