FROM python3-base
ARG TZ
ENV TZ=${TZ:-Asia/Taipei}
RUN DEBIAN_FRONTEND=noninteractive apt-get update\
 && DEBIAN_FRONTEND=noninteractive apt-get install -y bash-completion\
 && DEBIAN_FRONTEND=noninteractive apt-get clean
RUN pip install --no-cache-dir ipython pudb pydevd
CMD bash